museui/muse-ui

src/dropDownMenu/dropDownMenu.vue, src/pagination/pagination.vue
1. 删掉dropdown组件的打印
2. 修复pagination的一个bug，如题所示
=> pagination: 修复修改defaultPageSize或者pageSize的时候不生效的问题

src/pagination/pagination.vue, src/textField/enhancedTextarea.vue
1. 修复pagination的total和pageSize改变的时候因为current没有改变导致不去更新相关联的参数的问题
2. 修复text-field多行禁用的时候还可以输入的问题
=> pagination&text-field

src-docs/views/components/flatButton/exampleSimple.vue, src-docs/views/components/raisedButton/exampleSimple.vue
=> button: 修复button文档在Firefox显示不正常的问题

src-docs/views/components/pagination/pageSizeChange.vue, src/pagination/pagination.vue
=> fix(pagination): fix issue#252

src/infiniteScroll/infiniteScroll.vue
=> infiniteScroll: fix scrollbar bounce

src/table/th.vue
=> table: fix th text-overflow

src/autoComplete/autoComplete.vue, src/textField/enhancedTextarea.vue, src/textField/textField.vue
=> Fix autocomplete focus issue #495

src/dialog/dialog.vue, src/internal/popup/index.js, src/popover/popover.vue, src/popup/popup.vue
=> Removes components that use the popup mixin from the DOM when open property is false

src-docs/views/components/flexbox/zh.js
=> Just fixed a typing error.

src-docs/views/components/textField/api.js, src-docs/views/components/textField/en.js, src-docs/views/components/textField/zh.js, src/textField/enhancedTextarea.vue, src/textField/textField.vue
=> [WIP] Feature add required to text field

src/datePicker/calendar.vue, src/datePicker/datePicker.vue, src/datePicker/datePickerDialog.vue
暴露年份与月份的变更事件(yearChange、monthChange) 及dismiss事件
=> 暴露年份与月份的变更事件(yearChange、monthChange) 及dismiss事件

src/textField/textFieldHint.vue
=> fixed textFieldHint text overflow

src-docs/components/AppNavDrawer.vue, src-docs/router.js, src-docs/views/components/backTop/api.js, src-docs/views/components/backTop/en.js, src-docs/views/components/backTop/zh.js, src-docs/views/components/breadcrumb/README.md, src-docs/views/components/breadcrumb/README_EN.md, src-docs/views/components/breadcrumb/api.js, src-docs/views/components/breadcrumb/defineExample.vue, src-docs/views/components/breadcrumb/en.js, src-docs/views/components/breadcrumb/example.vue, src-docs/views/components/breadcrumb/index.vue, src-docs/views/components/breadcrumb/zh.js, src/breadCrumb/breadcrumb.vue, src/breadCrumb/breadcrumbItem.vue, src/breadCrumb/index.js, src/index.js
添加面包屑导航，效果如下图
此外计划加入musu-ui组织一起维护和开发这个项目，不知道作者意下如何:smile:
=> add component breadcrumb

src/table/table.vue
=> fix issue#536 table overlapping columns

src/textField/textField.vue
之前那个 close 了没法修改，有考虑不全的地方多谢指出来
=> textField: fix selectField can't select issue, see pull request #596

package-lock.json, src-docs/views/components/table/api.js, src-docs/views/components/table/exampleComplex.vue, src/table/table.vue, src/table/th.vue, src/table/thead.vue, src/table/tr.vue
This is a basic implementation of table sorting. As requested in https://github.com/museui/muse-ui/issues/276
please let me know if any changes/enhancements are needed
=> Add table sorting

src/datePicker/yearButton.vue
=> #732 修复选择年份自动关闭问题

src/popup/popup.vue
add an empty line in less code
=> popup: style the less code

less/theme-vars.less, less/theme.less, src-docs/views/components/iconButton/api.js, src-docs/views/components/iconButton/en.js, src-docs/views/components/iconButton/exampleSimple.vue, src-docs/views/components/iconButton/zh.js, src/iconButton/iconButton.vue, src/iconButton/theme.less, src/iconButton/var.less, src/styles/variables-theme.less
I think it would be nice that iconButton has same capabilities to handle "primary" and "secondary" settings as other button types. And also so that theming would work the same way.
=> iconButton: Added possibility to use primary and secondary properties.

src/timePicker/clockMinutes.vue
避免某些浏览器报"Duplicate data property"错误
=> 去掉多余的hasSelected

.gitignore, src-docs/views/components/autoComplete/exampleFilter.vue, src/autoComplete/autoComplete.vue, src/autoComplete/filters.js, src/menu/menuItem.vue
=> 完成feature autocomplete match text highlight

src/dialog/dialog.vue
The animation for opening the dialog didn't work properly in IE11, this is a fix for that.
=> dialog: IE11 fix for open dialog animation

docs/src/configs/i18n.js
=> docs: 修复了首页的文案错误

src/Picker/DatePicker/DayButton.js, src/utils/index.js
默认当前选中的样式为圆形的，如果需要为方形则需要重写以下CSS:
```css
.mu-datepicker-monthday-row {
height: 40px;
}
.mu-day-button-bg {
border-radius: 0;
height: 40px;
width: 50px;
left: 0;
}
.mu-day-button {
padding: 0px;
width: 50px;
}
.mu-day-empty {
width: 50px;
}
```
Closes #1134
=> feat(date): 新增日期控件DayButton自定义slot: day

src/Select/mixins/keyboard.js
Firefox didn't work with choosing options using keyboard
=> Select: Fixed undefined event variable

demo/App.vue, src/TextField/TextField.js
给 textfield 组件添加 focus 方法，使元素获得焦点，并在禁用时不触发
=> feat: add focus method to textfield
